
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var Webjump\Todo\ViewModel\Todo $todoVm */

$todoVm = $block->getData('todo_vm');

?>


<div class="todo_list">
    <div class="todo_component" data-bind="scope: 'todo_component'"  >
        <!-- ko template: getTemplate() --> <!-- /ko -->
    </div>
</div>


<script type="text/x-magento-init">
    {
        ".todo_component": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo_component": {
                        "component": "Webjump_Todo/js/todo_component",
                        "totalDefaultTodo": <?= $todoVm->getTotalDefaultTodo() ?>,
                        "optionsPagination": <?= json_encode($todoVm->getOptionTodos()) ?>
                    }
                }
            }
        }
    }
</script>
